# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

<color=#1C9F99>Beeheim Vanilla Plus</color>:
  address: beeheim.buzz
  port: 2406
  password: potat
  iswhitelisted: true